### ISSUE TITLE
Testing the comments on the feeback

### ISSUE THREAD

**Issue by jamatya** [QED-DeveloperPortal/qed-developer-portal#738]
Testing the comments on the Feedback 

 Submitted by - sushma-hazari-qed 
 Email address - Sushma.HAZARI@qed.qld.gov.au

**Comment by sushma-hazari-qed** [comment]
Adding comments on the Feedback and testing the count to be increased

**Comment by sushma-hazari-qed** [comment]
Testing the count of comments
